import { Destination, FlowerType, Month, Region } from "@/lib/types";

export const MONTHS: Month[] = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const REGIONS: Region[] = [
  "North America",
  "South America",
  "Europe",
  "Asia",
  "Africa",
  "Oceania",
];

export const FLOWER_TYPES: FlowerType[] = [
  "Cherry Blossom",
  "Tulip",
  "Lavender",
  "Sunflower",
  "Rose",
  "Jacaranda",
  "Wildflower",
  "Wisteria",
  "Hydrangea",
  "Lotus",
  "Canola",
  "Protea",
];

export const DESTINATIONS: Destination[] = [
  {
    id: "kyoto-japan",
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    flowerType: "Cherry Blossom",
    bloomMonths: [3, 4],
    peakMonths: [4],
    coordinates: { lat: 35.01, lng: 135.76 },
    shortDescription: "Historic temple gardens washed in blush-pink sakura.",
    longDescription:
      "Kyoto pairs iconic hanami scenes with quieter temple paths, riverside walks, and lantern-lit evenings under cherry blossom canopies.",
    signatureExperience: "Dawn blossom viewing along the Philosopher's Path.",
    travelTip: "Arrive early for temple gardens; petals peak quickly once warm weather settles in.",
    image: { from: "#f7d7db", to: "#f4eee9" },
  },
  {
    id: "hitachinaka-japan",
    name: "Hitachinaka",
    country: "Japan",
    region: "Asia",
    flowerType: "Wildflower",
    bloomMonths: [4, 5, 10],
    peakMonths: [5, 10],
    coordinates: { lat: 36.4, lng: 140.59 },
    shortDescription: "Rolling hills of blue nemophila and autumn kochia.",
    longDescription:
      "Hitachi Seaside Park is known for cinematic fields that shift by season, with blue nemophila in spring and scarlet kochia in autumn.",
    signatureExperience: "Walking the crest of Miharashi Hill at peak blue bloom.",
    travelTip: "Weekdays are calmer; spring winds can still feel chilly near the coast.",
    image: { from: "#d7ebfa", to: "#eef5f7" },
  },
  {
    id: "lisse-netherlands",
    name: "Lisse",
    country: "Netherlands",
    region: "Europe",
    flowerType: "Tulip",
    bloomMonths: [3, 4, 5],
    peakMonths: [4],
    coordinates: { lat: 52.26, lng: 4.56 },
    shortDescription: "Classic striped tulip fields and formal spring gardens.",
    longDescription:
      "Lisse offers the quintessential tulip trip, with curated garden displays at Keukenhof and broad bands of commercial tulip fields nearby.",
    signatureExperience: "Cycling past multicolored bulb fields just after sunrise.",
    travelTip: "April is safest for peak color; check wind and rain forecasts before booking bikes.",
    image: { from: "#f6d4ba", to: "#fff3e9" },
  },
  {
    id: "provence-france",
    name: "Valensole",
    country: "France",
    region: "Europe",
    flowerType: "Lavender",
    bloomMonths: [6, 7],
    peakMonths: [7],
    coordinates: { lat: 43.84, lng: 5.98 },
    shortDescription: "Long lavender rows, warm stone villages, and golden evening light.",
    longDescription:
      "The Valensole Plateau is one of the most romantic summer bloom escapes, with fragrant fields stretching between hilltop villages.",
    signatureExperience: "Golden-hour drives through the plateau with stops at small distilleries.",
    travelTip: "Go in early July for the strongest mix of color and fragrance before harvest.",
    image: { from: "#d6c7f2", to: "#f6ecff" },
  },
  {
    id: "furano-japan",
    name: "Furano",
    country: "Japan",
    region: "Asia",
    flowerType: "Lavender",
    bloomMonths: [6, 7, 8],
    peakMonths: [7],
    coordinates: { lat: 43.34, lng: 142.38 },
    shortDescription: "Lavender, patchwork flower farms, and broad Hokkaido skies.",
    longDescription:
      "Furano layers lavender with rainbow flower beds and countryside views, making it a soft, scenic midsummer alternative to city-based bloom trips.",
    signatureExperience: "Train and farm-hopping through central Hokkaido in mid-July.",
    travelTip: "Book accommodation well ahead for July weekends; car access makes the region easier.",
    image: { from: "#cfc9f7", to: "#edf3ff" },
  },
  {
    id: "castelluccio-italy",
    name: "Castelluccio",
    country: "Italy",
    region: "Europe",
    flowerType: "Wildflower",
    bloomMonths: [6, 7],
    peakMonths: [6],
    coordinates: { lat: 42.82, lng: 13.2 },
    shortDescription: "Alpine meadows filled with wild poppies, cornflowers, and daisies.",
    longDescription:
      "The Piano Grande near Castelluccio becomes a dramatic mosaic of mountain wildflowers each early summer, framed by high Apennine ridges.",
    signatureExperience: "A slow road trip across the plain as the colors spread across the valley floor.",
    travelTip: "Weather changes quickly at altitude, so layer clothing even on sunny days.",
    image: { from: "#f3d0d4", to: "#fcf6da" },
  },
  {
    id: "chiang-mai-thailand",
    name: "Chiang Mai",
    country: "Thailand",
    region: "Asia",
    flowerType: "Rose",
    bloomMonths: [12, 1, 2],
    peakMonths: [1],
    coordinates: { lat: 18.79, lng: 98.98 },
    shortDescription: "Cool-season gardens, rose festivals, and mountain air.",
    longDescription:
      "Northern Thailand's cooler months bring rose gardens into focus, especially around local winter flower festivals and royal project gardens.",
    signatureExperience: "Combining mountain viewpoints with the Chiang Mai Flower Festival.",
    travelTip: "January offers the cleanest weather and strongest bloom conditions.",
    image: { from: "#f1c7cd", to: "#f9f1ea" },
  },
  {
    id: "luoping-china",
    name: "Luoping",
    country: "China",
    region: "Asia",
    flowerType: "Canola",
    bloomMonths: [2, 3],
    peakMonths: [3],
    coordinates: { lat: 24.88, lng: 104.31 },
    shortDescription: "Vast yellow canola fields around limestone peaks.",
    longDescription:
      "Luoping's canola bloom is one of Asia's most dramatic agricultural flower landscapes, with bright yellow fields wrapped around karst hills.",
    signatureExperience: "Sunrise viewpoints over a patchwork of yellow fields and misty rock formations.",
    travelTip: "March is best, though late February can be excellent in warmer years.",
    image: { from: "#faef9c", to: "#fff9df" },
  },
  {
    id: "washington-dc-usa",
    name: "Washington, D.C.",
    country: "United States",
    region: "North America",
    flowerType: "Cherry Blossom",
    bloomMonths: [3, 4],
    peakMonths: [3],
    coordinates: { lat: 38.9, lng: -77.04 },
    shortDescription: "Monuments and tidal basin paths surrounded by pale blossoms.",
    longDescription:
      "The capital's cherry blossom season is compact, photogenic, and ideal for a short spring city break centered on the Tidal Basin.",
    signatureExperience: "Early-morning walks before the crowds gather around the water.",
    travelTip: "Peak timing shifts yearly, so flexible dates help if you're planning far ahead.",
    image: { from: "#f9dadd", to: "#f5f4ef" },
  },
  {
    id: "skagit-valley-usa",
    name: "Skagit Valley",
    country: "United States",
    region: "North America",
    flowerType: "Tulip",
    bloomMonths: [4],
    peakMonths: [4],
    coordinates: { lat: 48.42, lng: -122.34 },
    shortDescription: "Northwest tulip fields with snow-capped mountain backdrops.",
    longDescription:
      "Skagit Valley offers a moodier, maritime take on tulip season, with farms, local roads, and mountain views replacing formal European gardens.",
    signatureExperience: "A slow drive through the valley on a bright April afternoon.",
    travelTip: "Spring weather is variable; waterproof footwear makes the experience more comfortable.",
    image: { from: "#f5c6b8", to: "#e9f4ef" },
  },
  {
    id: "namaqualand-south-africa",
    name: "Namaqualand",
    country: "South Africa",
    region: "Africa",
    flowerType: "Wildflower",
    bloomMonths: [8, 9],
    peakMonths: [8],
    coordinates: { lat: -30.0, lng: 17.0 },
    shortDescription: "Desert plains transformed by bright spring daisies.",
    longDescription:
      "Namaqualand's wildflower super bloom is one of the Southern Hemisphere's iconic seasonal spectacles, especially after good winter rains.",
    signatureExperience: "Road-tripping between reserves as fields open in the midday sun.",
    travelTip: "Flowers often respond best to sunshine, so cloud cover can affect the experience.",
    image: { from: "#f4c66c", to: "#fff4d7" },
  },
  {
    id: "pretoria-south-africa",
    name: "Pretoria",
    country: "South Africa",
    region: "Africa",
    flowerType: "Jacaranda",
    bloomMonths: [10, 11],
    peakMonths: [10],
    coordinates: { lat: -25.75, lng: 28.19 },
    shortDescription: "Jacaranda-lined avenues in soft violet spring bloom.",
    longDescription:
      "Pretoria's tree-lined streets become a luminous purple canopy in spring, ideal for a city break with a distinct seasonal identity.",
    signatureExperience: "Neighborhood walks under jacaranda tunnels after a light rain.",
    travelTip: "Late October often brings the strongest color without early-season patchiness.",
    image: { from: "#d8c4f8", to: "#f8efff" },
  },
  {
    id: "mendoza-argentina",
    name: "Mendoza",
    country: "Argentina",
    region: "South America",
    flowerType: "Rose",
    bloomMonths: [10, 11, 12],
    peakMonths: [11],
    coordinates: { lat: -32.89, lng: -68.84 },
    shortDescription: "Rose gardens framed by vineyards and the Andes.",
    longDescription:
      "Mendoza combines floral city parks with wine country, making it a refined spring choice in the Southern Hemisphere.",
    signatureExperience: "Pairing rose garden mornings with relaxed winery afternoons.",
    travelTip: "November is especially balanced for flowers, weather, and vineyard visits.",
    image: { from: "#f2d0d5", to: "#fbf1e4" },
  },
  {
    id: "goryokaku-japan",
    name: "Hakodate",
    country: "Japan",
    region: "Asia",
    flowerType: "Cherry Blossom",
    bloomMonths: [4, 5],
    peakMonths: [5],
    coordinates: { lat: 41.77, lng: 140.73 },
    shortDescription: "Late cherry blossoms circling a star-shaped fort park.",
    longDescription:
      "Hakodate is ideal for travelers who miss central Japan's sakura season and want a cooler, slightly later blossom trip in Hokkaido.",
    signatureExperience: "Viewing the fort's blossom geometry from the tower above.",
    travelTip: "Early May is typically strongest; evenings near the bay can be cold.",
    image: { from: "#f8d9df", to: "#eef3f8" },
  },
  {
    id: "blue-mountains-australia",
    name: "Blue Mountains",
    country: "Australia",
    region: "Oceania",
    flowerType: "Hydrangea",
    bloomMonths: [12, 1, 2],
    peakMonths: [1],
    coordinates: { lat: -33.71, lng: 150.31 },
    shortDescription: "Cool-climate summer hydrangeas in misty garden towns.",
    longDescription:
      "The Blue Mountains offer an understated floral escape with garden estates, cliff views, and lush summer hydrangea displays.",
    signatureExperience: "Garden hopping through Leura and nearby villages on a cool summer day.",
    travelTip: "January brings fuller hydrangea heads, but weekends can be busy with local visitors.",
    image: { from: "#bfdcf2", to: "#f1f8fb" },
  },
  {
    id: "kawachi-japan",
    name: "Kitakyushu",
    country: "Japan",
    region: "Asia",
    flowerType: "Wisteria",
    bloomMonths: [4, 5],
    peakMonths: [5],
    coordinates: { lat: 33.87, lng: 130.82 },
    shortDescription: "Romantic wisteria tunnels and cascading pastel blooms.",
    longDescription:
      "Kawachi Fuji Garden near Kitakyushu is famed for immersive wisteria tunnels that turn late spring into a theatrical flower trip.",
    signatureExperience: "Timed-entry strolls beneath trailing wisteria curtains.",
    travelTip: "Peak color can compress into a short window, so mid to late April flexibility helps.",
    image: { from: "#dcccf8", to: "#fbf8ff" },
  },
];
