import { ConfidenceLevel, Destination, DestinationBadge, FlowerType, Month, Region } from "@/lib/types";

type RawFlowerType =
  | "Cherry Blossom"
  | "Tulip"
  | "Lavender"
  | "Sunflower"
  | "Canola"
  | "Rapeseed"
  | "Wildflower"
  | "Wisteria"
  | "Hydrangea"
  | "Rose"
  | "Jacaranda"
  | "Plum Blossom"
  | "Cosmos"
  | "Protea";

interface RawBloomDestination {
  id: string;
  destination: string;
  country: string;
  region: Region;
  latitude: number;
  longitude: number;
  flowerType: RawFlowerType;
  bloomStartMonth: number;
  bloomEndMonth: number;
  bestViewingMonth: number;
  bestViewingText: string;
  peakWindow: string;
  confidence: ConfidenceLevel;
  variabilityNote: string;
  shortDescription: string;
  whyVisit: string;
  travelTags: string[];
  bestTripLength: string;
  imageHint: string;
}

export const MONTHS: Month[] = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const REGIONS: Region[] = [
  "North America",
  "South America",
  "Europe",
  "Asia",
  "Africa",
  "Oceania",
];

export const FLOWER_TYPES: FlowerType[] = [
  "Cherry Blossom",
  "Tulip",
  "Lavender",
  "Sunflower",
  "Canola",
  "Rapeseed",
  "Wisteria",
  "Hydrangea",
  "Rose",
  "Jacaranda",
  "Plum Blossom",
  "Cosmos",
];

const FLOWER_GRADIENTS: Record<FlowerType, { from: string; to: string }> = {
  "Cherry Blossom": { from: "#f7d7df", to: "#f7f0eb" },
  Tulip: { from: "#f5c6b8", to: "#fff2e7" },
  Lavender: { from: "#d6c7f2", to: "#f3ebff" },
  Sunflower: { from: "#f6dc7a", to: "#fff6d1" },
  Rose: { from: "#f2d3da", to: "#faf2ea" },
  Jacaranda: { from: "#d8c4f8", to: "#f7f0ff" },
  "Plum Blossom": { from: "#f4c7d8", to: "#fff1f7" },
  Cosmos: { from: "#f5c4d5", to: "#fff4fb" },
  Wildflower: { from: "#f3d0d4", to: "#fcf6da" },
  Wisteria: { from: "#dcccf8", to: "#fbf8ff" },
  Hydrangea: { from: "#c4dff5", to: "#eef7fb" },
  Lotus: { from: "#f5d6df", to: "#edf5e1" },
  Canola: { from: "#faef9c", to: "#fff9df" },
  Rapeseed: { from: "#f6e68c", to: "#fff8dc" },
  Protea: { from: "#f2cdbb", to: "#f9efe5" },
};

function getBloomMonths(start: number, end: number) {
  if (start <= end) {
    return Array.from({ length: end - start + 1 }, (_, index) => start + index);
  }

  return [...Array.from({ length: 12 - start + 1 }, (_, index) => start + index), ...Array.from({ length: end }, (_, index) => index + 1)];
}

function getMonthLabel(month: number) {
  return MONTHS[month - 1];
}

function getBadges(tags: string[], bestTripLength: string, confidence: ConfidenceLevel): DestinationBadge[] {
  const badges: DestinationBadge[] = [];

  if (tags.includes("iconic")) {
    badges.push("Iconic");
  }
  if (tags.includes("romantic")) {
    badges.push("Romantic");
  }
  if (tags.includes("city") || tags.includes("city escape") || tags.includes("walkable")) {
    badges.push("City Escape");
  }
  if (
    tags.includes("nature") ||
    tags.includes("mountain") ||
    tags.includes("island") ||
    tags.includes("road trip") ||
    tags.includes("coastal") ||
    tags.includes("scenic") ||
    tags.includes("park")
  ) {
    badges.push("Nature Escape");
  }
  if (
    tags.includes("easy trip") ||
    tags.includes("family friendly") ||
    tags.includes("festival") ||
    bestTripLength.includes("1–2") ||
    bestTripLength.includes("2–4") ||
    bestTripLength.includes("2–3") ||
    bestTripLength.includes("3–4")
  ) {
    badges.push("Best 3-5 Day Trip");
  }
  if (confidence === "high" && !badges.includes("Iconic")) {
    badges.unshift("Iconic");
  }

  return Array.from(new Set(badges)).slice(0, 4);
}

const RAW_DESTINATIONS: RawBloomDestination[] = [
  {
    id: "tokyo-cherry-blossom",
    destination: "Tokyo",
    country: "Japan",
    region: "Asia",
    latitude: 35.6762,
    longitude: 139.6503,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 3,
    bestViewingText: "Late March to early April",
    peakWindow: "Final week of March",
    confidence: "medium",
    variabilityNote: "Timing shifts slightly with spring temperatures.",
    shortDescription: "A classic urban sakura season with parks, riversides, and iconic city views.",
    whyVisit: "Best for travelers who want a famous spring bloom experience with easy city access.",
    travelTags: ["iconic", "city", "romantic"],
    bestTripLength: "4–6 days",
    imageHint: "Tokyo cherry blossoms along river in spring",
  },
  {
    id: "kyoto-cherry-blossom",
    destination: "Kyoto",
    country: "Japan",
    region: "Asia",
    latitude: 35.0116,
    longitude: 135.7681,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "Late March to early April",
    peakWindow: "Early April",
    confidence: "medium",
    variabilityNote: "Peak bloom varies by temple garden and elevation.",
    shortDescription: "Historic temples and quiet lanes frame one of the most atmospheric blossom seasons in Japan.",
    whyVisit: "Great for travelers who want traditional scenery and a softer, more reflective sakura trip.",
    travelTags: ["iconic", "historic", "romantic"],
    bestTripLength: "3–5 days",
    imageHint: "Kyoto temple cherry blossoms spring",
  },
  {
    id: "osaka-cherry-blossom",
    destination: "Osaka",
    country: "Japan",
    region: "Asia",
    latitude: 34.6937,
    longitude: 135.5023,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "Late March to early April",
    peakWindow: "Early April",
    confidence: "medium",
    variabilityNote: "Urban heat can slightly advance bloom timing.",
    shortDescription: "A lively blossom stop known for castle grounds and easy food-focused city breaks.",
    whyVisit: "A practical sakura destination if you want both spring scenery and a casual city trip.",
    travelTags: ["city", "food", "easy trip"],
    bestTripLength: "3–4 days",
    imageHint: "Osaka castle cherry blossoms",
  },
  {
    id: "hirosaki-cherry-blossom",
    destination: "Hirosaki",
    country: "Japan",
    region: "Asia",
    latitude: 40.6031,
    longitude: 140.4642,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 4,
    bloomEndMonth: 5,
    bestViewingMonth: 4,
    bestViewingText: "Late April",
    peakWindow: "Last week of April",
    confidence: "medium",
    variabilityNote: "Northern climate usually delays bloom compared with Tokyo and Kyoto.",
    shortDescription: "A famous northern castle park destination with dense cherry blossoms and moats lined in petals.",
    whyVisit: "Ideal if you miss central Japan's sakura season and want a later bloom option.",
    travelTags: ["iconic", "nature", "photogenic"],
    bestTripLength: "2–4 days",
    imageHint: "Hirosaki castle cherry blossom moat",
  },
  {
    id: "seoul-cherry-blossom",
    destination: "Seoul",
    country: "South Korea",
    region: "Asia",
    latitude: 37.5665,
    longitude: 126.978,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "Early April",
    peakWindow: "First half of April",
    confidence: "medium",
    variabilityNote: "Timing depends on year-to-year spring warmth.",
    shortDescription: "Riverside parks and palace grounds make Seoul a strong city-based blossom destination.",
    whyVisit: "A good choice for travelers who want cherry blossom season with a modern city rhythm.",
    travelTags: ["city", "romantic", "easy trip"],
    bestTripLength: "4–5 days",
    imageHint: "Seoul cherry blossom city park",
  },
  {
    id: "jinhae-cherry-blossom",
    destination: "Jinhae",
    country: "South Korea",
    region: "Asia",
    latitude: 35.1498,
    longitude: 128.6592,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "Early April",
    peakWindow: "Early April",
    confidence: "medium",
    variabilityNote: "Festival timing can influence crowd levels more than bloom timing itself.",
    shortDescription: "One of Korea's best-known blossom destinations, especially for dramatic rail and stream views.",
    whyVisit: "Best for a high-impact spring bloom trip with strong visual payoff.",
    travelTags: ["iconic", "festival", "photogenic"],
    bestTripLength: "2–3 days",
    imageHint: "Jinhae cherry blossom festival stream",
  },
  {
    id: "washington-dc-cherry-blossom",
    destination: "Washington, D.C.",
    country: "United States",
    region: "North America",
    latitude: 38.9072,
    longitude: -77.0369,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 3,
    bestViewingText: "Late March to early April",
    peakWindow: "Late March",
    confidence: "medium",
    variabilityNote: "Bloom timing varies with winter and early spring weather patterns.",
    shortDescription: "A landmark blossom season around the Tidal Basin with monuments and broad pedestrian views.",
    whyVisit: "A strong spring city trip if you want iconic blossom scenery in a compact destination.",
    travelTags: ["iconic", "city", "historic"],
    bestTripLength: "3–4 days",
    imageHint: "Washington DC tidal basin cherry blossoms",
  },
  {
    id: "vancouver-cherry-blossom",
    destination: "Vancouver",
    country: "Canada",
    region: "North America",
    latitude: 49.2827,
    longitude: -123.1207,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "Early to mid April",
    peakWindow: "Early April",
    confidence: "medium",
    variabilityNote: "Different neighborhoods and varieties bloom at different times.",
    shortDescription: "A gentle spring bloom season with residential streets, waterfront walks, and mountain backdrops.",
    whyVisit: "Great for travelers who want a calm, scenic blossom trip without a festival-heavy atmosphere.",
    travelTags: ["city", "nature", "relaxed"],
    bestTripLength: "3–5 days",
    imageHint: "Vancouver cherry blossoms street spring",
  },
  {
    id: "taipei-cherry-blossom",
    destination: "Taipei",
    country: "Taiwan",
    region: "Asia",
    latitude: 25.033,
    longitude: 121.5654,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 1,
    bloomEndMonth: 3,
    bestViewingMonth: 2,
    bestViewingText: "February",
    peakWindow: "Mid February",
    confidence: "medium",
    variabilityNote: "Mountain viewing areas can bloom later than city-adjacent spots.",
    shortDescription: "An earlier blossom season that works well for late-winter travel in East Asia.",
    whyVisit: "Useful if you want cherry blossom travel earlier than Japan or Korea.",
    travelTags: ["early season", "city", "easy trip"],
    bestTripLength: "3–5 days",
    imageHint: "Taipei cherry blossom mountain park",
  },
  {
    id: "alishan-cherry-blossom",
    destination: "Alishan",
    country: "Taiwan",
    region: "Asia",
    latitude: 23.5101,
    longitude: 120.805,
    flowerType: "Cherry Blossom",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 3,
    bestViewingText: "Late March",
    peakWindow: "Late March",
    confidence: "medium",
    variabilityNote: "Elevation affects bloom timing and morning visibility.",
    shortDescription: "A mountain blossom experience with misty forest rail scenery and cool spring air.",
    whyVisit: "Best for travelers who want cherry blossoms in a nature-first setting.",
    travelTags: ["nature", "mountain", "scenic"],
    bestTripLength: "2–3 days",
    imageHint: "Alishan Taiwan cherry blossom mountain railway",
  },
  {
    id: "keukenhof-tulip",
    destination: "Lisse",
    country: "Netherlands",
    region: "Europe",
    latitude: 52.2712,
    longitude: 4.546,
    flowerType: "Tulip",
    bloomStartMonth: 3,
    bloomEndMonth: 5,
    bestViewingMonth: 4,
    bestViewingText: "April",
    peakWindow: "Mid April",
    confidence: "high",
    variabilityNote: "Weather influences field intensity, but the main season is generally reliable.",
    shortDescription: "The classic tulip destination with layered color, curated gardens, and easy access from Amsterdam.",
    whyVisit: "The most recognizable tulip trip for travelers who want a polished, iconic floral experience.",
    travelTags: ["iconic", "romantic", "easy trip"],
    bestTripLength: "2–4 days",
    imageHint: "Keukenhof tulip gardens spring",
  },
  {
    id: "haarlem-tulip",
    destination: "Haarlem",
    country: "Netherlands",
    region: "Europe",
    latitude: 52.3874,
    longitude: 4.6462,
    flowerType: "Tulip",
    bloomStartMonth: 3,
    bloomEndMonth: 5,
    bestViewingMonth: 4,
    bestViewingText: "April",
    peakWindow: "Mid April",
    confidence: "high",
    variabilityNote: "Field color can vary by year and planting cycle.",
    shortDescription: "A strong base for seeing Dutch tulip fields with a quieter town feel than central Amsterdam.",
    whyVisit: "A good tulip choice if you want field access and a more relaxed local base.",
    travelTags: ["relaxed", "scenic", "easy trip"],
    bestTripLength: "2–3 days",
    imageHint: "Haarlem tulip fields netherlands",
  },
  {
    id: "ottawa-tulip",
    destination: "Ottawa",
    country: "Canada",
    region: "North America",
    latitude: 45.4215,
    longitude: -75.6972,
    flowerType: "Tulip",
    bloomStartMonth: 5,
    bloomEndMonth: 5,
    bestViewingMonth: 5,
    bestViewingText: "Mid May",
    peakWindow: "Mid May",
    confidence: "medium",
    variabilityNote: "Spring warmth can shift peak festival color slightly earlier or later.",
    shortDescription: "A compact spring city trip centered around public tulip displays and waterways.",
    whyVisit: "Best for an easy North American flower trip with city comfort and festival atmosphere.",
    travelTags: ["city", "festival", "easy trip"],
    bestTripLength: "2–4 days",
    imageHint: "Ottawa tulip festival spring",
  },
  {
    id: "skagit-tulip",
    destination: "Skagit Valley",
    country: "United States",
    region: "North America",
    latitude: 48.4245,
    longitude: -122.334,
    flowerType: "Tulip",
    bloomStartMonth: 4,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "April",
    peakWindow: "Mid April",
    confidence: "medium",
    variabilityNote: "Field timing depends strongly on seasonal weather and farm conditions.",
    shortDescription: "Wide tulip fields under open sky with a more rural, road-trip-friendly feel.",
    whyVisit: "Great if you want colorful spring fields rather than formal gardens.",
    travelTags: ["nature", "road trip", "photogenic"],
    bestTripLength: "2–3 days",
    imageHint: "Skagit Valley tulip fields",
  },
  {
    id: "istanbul-tulip",
    destination: "Istanbul",
    country: "Turkey",
    region: "Europe",
    latitude: 41.0082,
    longitude: 28.9784,
    flowerType: "Tulip",
    bloomStartMonth: 4,
    bloomEndMonth: 4,
    bestViewingMonth: 4,
    bestViewingText: "April",
    peakWindow: "Mid April",
    confidence: "medium",
    variabilityNote: "Public display quality varies slightly by park and spring conditions.",
    shortDescription: "An urban tulip season spread through large parks and historic city settings.",
    whyVisit: "A good option if you want spring flowers combined with major cultural sightseeing.",
    travelTags: ["city", "historic", "iconic"],
    bestTripLength: "4–5 days",
    imageHint: "Istanbul tulip festival park",
  },
  {
    id: "provence-lavender",
    destination: "Valensole",
    country: "France",
    region: "Europe",
    latitude: 43.8363,
    longitude: 5.9833,
    flowerType: "Lavender",
    bloomStartMonth: 6,
    bloomEndMonth: 7,
    bestViewingMonth: 7,
    bestViewingText: "Early to mid July",
    peakWindow: "First half of July",
    confidence: "medium",
    variabilityNote: "Harvest timing can shorten the visual peak depending on the season.",
    shortDescription: "Rolling purple fields and open Provencal landscapes make this a signature summer flower trip.",
    whyVisit: "The best-known lavender journey for travelers chasing a cinematic summer landscape.",
    travelTags: ["iconic", "romantic", "road trip"],
    bestTripLength: "3–5 days",
    imageHint: "Provence lavender fields Valensole",
  },
  {
    id: "sault-lavender",
    destination: "Sault",
    country: "France",
    region: "Europe",
    latitude: 44.0908,
    longitude: 5.4099,
    flowerType: "Lavender",
    bloomStartMonth: 7,
    bloomEndMonth: 8,
    bestViewingMonth: 7,
    bestViewingText: "Mid July",
    peakWindow: "Mid July",
    confidence: "medium",
    variabilityNote: "Higher elevation can shift bloom slightly later than lower Provence fields.",
    shortDescription: "A quieter lavender region with mountain influence and slower-paced summer travel.",
    whyVisit: "Ideal if you like lavender but want a less crowded alternative to Valensole.",
    travelTags: ["relaxed", "nature", "scenic"],
    bestTripLength: "2–4 days",
    imageHint: "Sault France lavender fields",
  },
  {
    id: "furano-lavender",
    destination: "Furano",
    country: "Japan",
    region: "Asia",
    latitude: 43.3425,
    longitude: 142.3832,
    flowerType: "Lavender",
    bloomStartMonth: 7,
    bloomEndMonth: 8,
    bestViewingMonth: 7,
    bestViewingText: "Mid July",
    peakWindow: "Mid July",
    confidence: "high",
    variabilityNote: "Field variety timing differs, but the core season is fairly dependable.",
    shortDescription: "A much-loved Hokkaido summer destination with orderly lavender rows and broad rural scenery.",
    whyVisit: "A strong choice for travelers who want summer flowers with cooler weather and spacious views.",
    travelTags: ["iconic", "nature", "family friendly"],
    bestTripLength: "3–5 days",
    imageHint: "Furano lavender Hokkaido",
  },
  {
    id: "bridestowe-lavender",
    destination: "Bridestowe",
    country: "Australia",
    region: "Oceania",
    latitude: -41.0028,
    longitude: 147.3554,
    flowerType: "Lavender",
    bloomStartMonth: 12,
    bloomEndMonth: 1,
    bestViewingMonth: 12,
    bestViewingText: "Late December",
    peakWindow: "Late December",
    confidence: "medium",
    variabilityNote: "Southern Hemisphere timing is weather-sensitive but seasonally consistent.",
    shortDescription: "A Southern Hemisphere lavender trip that works well during northern winter holidays.",
    whyVisit: "Useful if you want a lavender-style trip when Europe is out of season.",
    travelTags: ["seasonal contrast", "nature", "scenic"],
    bestTripLength: "2–3 days",
    imageHint: "Tasmania lavender fields Bridestowe",
  },
  {
    id: "hokuryu-sunflower",
    destination: "Hokuryu",
    country: "Japan",
    region: "Asia",
    latitude: 43.7318,
    longitude: 141.8937,
    flowerType: "Sunflower",
    bloomStartMonth: 7,
    bloomEndMonth: 8,
    bestViewingMonth: 8,
    bestViewingText: "Early August",
    peakWindow: "Early August",
    confidence: "medium",
    variabilityNote: "Bloom intensity varies by planting section and weather.",
    shortDescription: "A cheerful summer flower stop known for broad sunflower fields in rural Hokkaido.",
    whyVisit: "Best for travelers who want a bright, high-summer landscape with a playful feel.",
    travelTags: ["nature", "summer", "photogenic"],
    bestTripLength: "2–3 days",
    imageHint: "Hokuryu sunflower village Hokkaido",
  },
  {
    id: "val-dorcia-sunflower",
    destination: "Val d'Orcia",
    country: "Italy",
    region: "Europe",
    latitude: 43.0621,
    longitude: 11.6186,
    flowerType: "Sunflower",
    bloomStartMonth: 6,
    bloomEndMonth: 7,
    bestViewingMonth: 7,
    bestViewingText: "July",
    peakWindow: "Early to mid July",
    confidence: "medium",
    variabilityNote: "Agricultural rotation means exact field locations may vary year to year.",
    shortDescription: "A scenic countryside region where sunflower fields appear alongside cypress roads and hill towns.",
    whyVisit: "Ideal for a road-trip-style summer bloom experience with strong landscape character.",
    travelTags: ["road trip", "romantic", "scenic"],
    bestTripLength: "3–5 days",
    imageHint: "Tuscany sunflower fields summer",
  },
  {
    id: "andalucia-sunflower",
    destination: "Carmona",
    country: "Spain",
    region: "Europe",
    latitude: 37.4713,
    longitude: -5.6461,
    flowerType: "Sunflower",
    bloomStartMonth: 5,
    bloomEndMonth: 6,
    bestViewingMonth: 6,
    bestViewingText: "June",
    peakWindow: "Mid June",
    confidence: "medium",
    variabilityNote: "Field appearance depends on agricultural timing and heat.",
    shortDescription: "Golden summer fields spread across open Andalusian countryside under strong southern light.",
    whyVisit: "A good sunflower trip if you prefer warm, expansive rural scenery.",
    travelTags: ["nature", "road trip", "summer"],
    bestTripLength: "2–4 days",
    imageHint: "Andalusia sunflower fields Spain",
  },
  {
    id: "luoping-canola",
    destination: "Luoping",
    country: "China",
    region: "Asia",
    latitude: 24.8847,
    longitude: 104.3075,
    flowerType: "Rapeseed",
    bloomStartMonth: 2,
    bloomEndMonth: 3,
    bestViewingMonth: 2,
    bestViewingText: "Late February to early March",
    peakWindow: "Late February",
    confidence: "medium",
    variabilityNote: "Flowering depends on regional weather and field conditions.",
    shortDescription: "Dramatic yellow canola fields set against karst hills make this one of China's strongest spring bloom landscapes.",
    whyVisit: "A standout pick if you want broad, cinematic flower scenery rather than formal gardens.",
    travelTags: ["iconic", "nature", "photogenic"],
    bestTripLength: "3–4 days",
    imageHint: "Luoping canola fields yellow karst hills",
  },
  {
    id: "wuyuan-canola",
    destination: "Wuyuan",
    country: "China",
    region: "Asia",
    latitude: 29.2479,
    longitude: 117.8617,
    flowerType: "Rapeseed",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 3,
    bestViewingText: "Mid to late March",
    peakWindow: "Late March",
    confidence: "medium",
    variabilityNote: "Village-by-village timing can shift slightly.",
    shortDescription: "Traditional white-walled villages sit among soft yellow spring fields in one of China's gentlest rural bloom destinations.",
    whyVisit: "Best for travelers who want flowers combined with village atmosphere and slower-paced scenery.",
    travelTags: ["historic", "nature", "scenic"],
    bestTripLength: "2–4 days",
    imageHint: "Wuyuan rapeseed flowers village China",
  },
  {
    id: "jeju-canola",
    destination: "Jeju",
    country: "South Korea",
    region: "Asia",
    latitude: 33.4996,
    longitude: 126.5312,
    flowerType: "Canola",
    bloomStartMonth: 3,
    bloomEndMonth: 4,
    bestViewingMonth: 3,
    bestViewingText: "Mid March",
    peakWindow: "Mid March",
    confidence: "medium",
    variabilityNote: "Coastal and inland locations may bloom at slightly different times.",
    shortDescription: "A bright early-spring island destination with yellow fields, ocean light, and easy road-trip energy.",
    whyVisit: "A strong choice if you want flowers plus an island escape feel.",
    travelTags: ["island", "nature", "romantic"],
    bestTripLength: "3–5 days",
    imageHint: "Jeju canola flowers coast",
  },
  {
    id: "abira-canola",
    destination: "Abira",
    country: "Japan",
    region: "Asia",
    latitude: 42.8216,
    longitude: 141.8184,
    flowerType: "Canola",
    bloomStartMonth: 5,
    bloomEndMonth: 6,
    bestViewingMonth: 5,
    bestViewingText: "Late May",
    peakWindow: "Late May",
    confidence: "medium",
    variabilityNote: "Spring progression in Hokkaido can move the season slightly.",
    shortDescription: "A fresh late-spring yellow field landscape in Hokkaido's open countryside.",
    whyVisit: "Useful as a later canola option after early spring destinations have passed.",
    travelTags: ["nature", "road trip", "seasonal contrast"],
    bestTripLength: "2–3 days",
    imageHint: "Hokkaido canola fields Abira",
  },
  {
    id: "ashikaga-wisteria",
    destination: "Ashikaga",
    country: "Japan",
    region: "Asia",
    latitude: 36.3148,
    longitude: 139.5774,
    flowerType: "Wisteria",
    bloomStartMonth: 4,
    bloomEndMonth: 5,
    bestViewingMonth: 5,
    bestViewingText: "Late April to early May",
    peakWindow: "Early May",
    confidence: "high",
    variabilityNote: "Different colored wisteria areas mature at slightly different times.",
    shortDescription: "A famous floral park known for immersive wisteria tunnels and hanging clusters.",
    whyVisit: "Best for a concentrated, highly visual spring flower experience.",
    travelTags: ["iconic", "romantic", "photogenic"],
    bestTripLength: "1–2 days",
    imageHint: "Ashikaga flower park wisteria tunnel",
  },
  {
    id: "kawachi-wisteria",
    destination: "Kitakyushu",
    country: "Japan",
    region: "Asia",
    latitude: 33.8833,
    longitude: 130.8752,
    flowerType: "Wisteria",
    bloomStartMonth: 4,
    bloomEndMonth: 5,
    bestViewingMonth: 5,
    bestViewingText: "Late April",
    peakWindow: "Final week of April",
    confidence: "medium",
    variabilityNote: "Public access windows may be narrower than the full season.",
    shortDescription: "A sought-after destination for dramatic wisteria tunnels and dense hanging blooms.",
    whyVisit: "A strong option if your app wants a highly shareable spring floral moment.",
    travelTags: ["iconic", "romantic", "limited access"],
    bestTripLength: "1–2 days",
    imageHint: "Kawachi Fuji Garden wisteria tunnel",
  },
  {
    id: "kamakura-hydrangea",
    destination: "Kamakura",
    country: "Japan",
    region: "Asia",
    latitude: 35.3193,
    longitude: 139.5467,
    flowerType: "Hydrangea",
    bloomStartMonth: 6,
    bloomEndMonth: 7,
    bestViewingMonth: 6,
    bestViewingText: "Mid to late June",
    peakWindow: "Late June",
    confidence: "medium",
    variabilityNote: "Rainfall and humidity influence freshness and color intensity.",
    shortDescription: "Temple paths and hillside gardens make Kamakura one of Japan's best-known rainy season flower destinations.",
    whyVisit: "Perfect for travelers who like moody seasonal atmosphere rather than peak spring crowds.",
    travelTags: ["historic", "romantic", "seasonal"],
    bestTripLength: "2–3 days",
    imageHint: "Kamakura hydrangea temple rainy season",
  },
  {
    id: "blue-mountains-hydrangea",
    destination: "Blue Mountains",
    country: "Australia",
    region: "Oceania",
    latitude: -33.712,
    longitude: 150.3119,
    flowerType: "Hydrangea",
    bloomStartMonth: 1,
    bloomEndMonth: 2,
    bestViewingMonth: 2,
    bestViewingText: "February",
    peakWindow: "Early February",
    confidence: "medium",
    variabilityNote: "Garden displays vary by altitude and summer rainfall.",
    shortDescription: "A cool-climate summer bloom destination with misty garden-town character.",
    whyVisit: "A nice Southern Hemisphere option for a short, romantic bloom break.",
    travelTags: ["romantic", "nature", "easy trip"],
    bestTripLength: "2–3 days",
    imageHint: "Blue Mountains hydrangea Australia",
  },
  {
    id: "sao-miguel-hydrangea",
    destination: "Sao Miguel",
    country: "Portugal",
    region: "Europe",
    latitude: 37.7412,
    longitude: -25.6756,
    flowerType: "Hydrangea",
    bloomStartMonth: 6,
    bloomEndMonth: 8,
    bestViewingMonth: 7,
    bestViewingText: "July",
    peakWindow: "Mid July",
    confidence: "medium",
    variabilityNote: "Roadside hedges and upland areas can peak at different moments.",
    shortDescription: "Hydrangeas line roads and volcanic landscapes across the islands during summer.",
    whyVisit: "Best for travelers who want flowers integrated into a broader scenic island trip.",
    travelTags: ["island", "nature", "road trip"],
    bestTripLength: "4–6 days",
    imageHint: "Azores hydrangea roadside summer",
  },
  {
    id: "madeira-hydrangea",
    destination: "Madeira",
    country: "Portugal",
    region: "Europe",
    latitude: 32.7607,
    longitude: -16.9595,
    flowerType: "Hydrangea",
    bloomStartMonth: 6,
    bloomEndMonth: 8,
    bestViewingMonth: 7,
    bestViewingText: "July",
    peakWindow: "July",
    confidence: "medium",
    variabilityNote: "Microclimates affect the strongest roadside and upland displays.",
    shortDescription: "An island garden destination where hydrangeas add color to mountain roads and lush landscapes.",
    whyVisit: "Strong for users who want flowers as part of a scenic island holiday rather than a single-site attraction.",
    travelTags: ["island", "nature", "road trip"],
    bestTripLength: "4–6 days",
    imageHint: "Madeira hydrangea mountain road",
  },
  {
    id: "kazanlak-rose",
    destination: "Kazanlak",
    country: "Bulgaria",
    region: "Europe",
    latitude: 42.62,
    longitude: 25.392,
    flowerType: "Rose",
    bloomStartMonth: 5,
    bloomEndMonth: 6,
    bestViewingMonth: 6,
    bestViewingText: "Early June",
    peakWindow: "First half of June",
    confidence: "medium",
    variabilityNote: "Harvest activity can shape the feel of the season.",
    shortDescription: "A distinctive flower region known for rose fields, fragrance traditions, and seasonal celebrations.",
    whyVisit: "A unique choice if you want a bloom trip tied to local craft and identity.",
    travelTags: ["cultural", "festival", "romantic"],
    bestTripLength: "2–4 days",
    imageHint: "Bulgaria rose valley bloom",
  },
  {
    id: "chiang-mai-rose",
    destination: "Chiang Mai",
    country: "Thailand",
    region: "Asia",
    latitude: 18.7883,
    longitude: 98.9853,
    flowerType: "Rose",
    bloomStartMonth: 12,
    bloomEndMonth: 2,
    bestViewingMonth: 1,
    bestViewingText: "January",
    peakWindow: "January",
    confidence: "medium",
    variabilityNote: "Garden quality is more reliable than wild or dispersed viewing.",
    shortDescription: "Cool-season gardens and flower festival energy make this a good winter flower stop.",
    whyVisit: "Works well for a warm-weather winter trip with a softer floral angle.",
    travelTags: ["city escape", "festival", "winter sun"],
    bestTripLength: "3–4 days",
    imageHint: "Chiang Mai flower festival roses",
  },
  {
    id: "portland-rose",
    destination: "Portland",
    country: "United States",
    region: "North America",
    latitude: 45.5152,
    longitude: -122.6784,
    flowerType: "Rose",
    bloomStartMonth: 5,
    bloomEndMonth: 9,
    bestViewingMonth: 6,
    bestViewingText: "June",
    peakWindow: "June",
    confidence: "medium",
    variabilityNote: "Garden roses continue through summer, though the strongest first flush arrives earlier.",
    shortDescription: "A long rose season centered on formal gardens and easy urban nature access.",
    whyVisit: "A practical flower city trip with reliable summer garden appeal.",
    travelTags: ["city", "garden", "easy trip"],
    bestTripLength: "2–4 days",
    imageHint: "Portland international rose test garden",
  },
  {
    id: "sydney-jacaranda",
    destination: "Sydney",
    country: "Australia",
    region: "Oceania",
    latitude: -33.8688,
    longitude: 151.2093,
    flowerType: "Jacaranda",
    bloomStartMonth: 10,
    bloomEndMonth: 11,
    bestViewingMonth: 11,
    bestViewingText: "Early November",
    peakWindow: "Early November",
    confidence: "medium",
    variabilityNote: "Neighborhood-by-neighborhood timing differs slightly.",
    shortDescription: "Purple-blossomed streets briefly transform selected parts of the city each spring.",
    whyVisit: "A great shoulder-season city trip if you like short but memorable bloom moments.",
    travelTags: ["city", "romantic", "photogenic"],
    bestTripLength: "3–5 days",
    imageHint: "Sydney jacaranda street bloom",
  },
  {
    id: "pretoria-jacaranda",
    destination: "Pretoria",
    country: "South Africa",
    region: "Africa",
    latitude: -25.7479,
    longitude: 28.2293,
    flowerType: "Jacaranda",
    bloomStartMonth: 10,
    bloomEndMonth: 11,
    bestViewingMonth: 10,
    bestViewingText: "October",
    peakWindow: "Mid October",
    confidence: "medium",
    variabilityNote: "Wind and early heat can shorten the most dramatic visual phase.",
    shortDescription: "A famous jacaranda city where spring streets take on a purple canopy effect.",
    whyVisit: "One of the strongest jacaranda-specific destinations for seasonal city imagery.",
    travelTags: ["iconic", "city", "seasonal"],
    bestTripLength: "2–3 days",
    imageHint: "Pretoria jacaranda avenue spring",
  },
  {
    id: "buenos-aires-jacaranda",
    destination: "Buenos Aires",
    country: "Argentina",
    region: "South America",
    latitude: -34.6037,
    longitude: -58.3816,
    flowerType: "Jacaranda",
    bloomStartMonth: 10,
    bloomEndMonth: 11,
    bestViewingMonth: 11,
    bestViewingText: "Early November",
    peakWindow: "Early November",
    confidence: "medium",
    variabilityNote: "Tree-by-tree timing can create a staggered city bloom effect.",
    shortDescription: "A stylish Southern Hemisphere spring city with lavender-toned avenues and parks.",
    whyVisit: "Best if you want jacarandas combined with a bigger city experience and strong street character.",
    travelTags: ["city", "romantic", "walkable"],
    bestTripLength: "4–5 days",
    imageHint: "Buenos Aires jacaranda trees bloom",
  },
  {
    id: "nanjing-plum-blossom",
    destination: "Nanjing",
    country: "China",
    region: "Asia",
    latitude: 32.0603,
    longitude: 118.7969,
    flowerType: "Plum Blossom",
    bloomStartMonth: 2,
    bloomEndMonth: 3,
    bestViewingMonth: 2,
    bestViewingText: "Late February",
    peakWindow: "Late February",
    confidence: "medium",
    variabilityNote: "Warmer winters can advance the season.",
    shortDescription: "One of East Asia's elegant late-winter flower traditions, with delicate blossoms before full spring arrives.",
    whyVisit: "A refined choice for travelers who like quiet seasonal transitions rather than peak tourism.",
    travelTags: ["historic", "early season", "calm"],
    bestTripLength: "2–3 days",
    imageHint: "Nanjing plum blossom garden",
  },
  {
    id: "atami-plum-blossom",
    destination: "Atami",
    country: "Japan",
    region: "Asia",
    latitude: 35.095,
    longitude: 139.068,
    flowerType: "Plum Blossom",
    bloomStartMonth: 1,
    bloomEndMonth: 2,
    bestViewingMonth: 2,
    bestViewingText: "Early February",
    peakWindow: "Early February",
    confidence: "medium",
    variabilityNote: "Some years begin notably early depending on winter temperatures.",
    shortDescription: "A mild coastal destination with one of Japan's earlier blossom seasons.",
    whyVisit: "Ideal for a gentle winter flower trip before the main sakura rush begins.",
    travelTags: ["early season", "coastal", "easy trip"],
    bestTripLength: "1–2 days",
    imageHint: "Atami plum blossom early spring",
  },
  {
    id: "seoul-cosmos",
    destination: "Seoul",
    country: "South Korea",
    region: "Asia",
    latitude: 37.5665,
    longitude: 126.978,
    flowerType: "Cosmos",
    bloomStartMonth: 9,
    bloomEndMonth: 10,
    bestViewingMonth: 10,
    bestViewingText: "October",
    peakWindow: "Early October",
    confidence: "medium",
    variabilityNote: "Urban park maintenance influences display quality.",
    shortDescription: "An early autumn flower layer that softens city parks after summer heat fades.",
    whyVisit: "A good shoulder-season alternative if users want color without peak spring crowds.",
    travelTags: ["city", "autumn", "easy trip"],
    bestTripLength: "2–4 days",
    imageHint: "Seoul cosmos flowers autumn park",
  },
  {
    id: "hitachi-cosmos",
    destination: "Hitachinaka",
    country: "Japan",
    region: "Asia",
    latitude: 36.4056,
    longitude: 140.5969,
    flowerType: "Cosmos",
    bloomStartMonth: 10,
    bloomEndMonth: 10,
    bestViewingMonth: 10,
    bestViewingText: "Mid October",
    peakWindow: "Mid October",
    confidence: "medium",
    variabilityNote: "Wind and weather exposure affect flower quality.",
    shortDescription: "A broad autumn flower display with hillside planting and easy day-trip access.",
    whyVisit: "A useful October destination if you want the app to feel lively beyond spring and summer.",
    travelTags: ["autumn", "park", "photogenic"],
    bestTripLength: "1–2 days",
    imageHint: "Hitachi cosmos autumn flower hill",
  },
  {
    id: "nami-cosmos",
    destination: "Nami Island",
    country: "South Korea",
    region: "Asia",
    latitude: 37.7909,
    longitude: 127.5259,
    flowerType: "Cosmos",
    bloomStartMonth: 9,
    bloomEndMonth: 10,
    bestViewingMonth: 10,
    bestViewingText: "Early October",
    peakWindow: "Early October",
    confidence: "medium",
    variabilityNote: "Season quality depends on yearly planting and weather.",
    shortDescription: "A gentle autumn day trip with flower fields and tree-lined walking routes.",
    whyVisit: "A softer, romantic option for users who like seasonal scenery near Seoul.",
    travelTags: ["romantic", "autumn", "easy trip"],
    bestTripLength: "1–2 days",
    imageHint: "Nami Island cosmos flowers autumn",
  },
  {
    id: "holland-michigan-tulip",
    destination: "Holland, Michigan",
    country: "United States",
    region: "North America",
    latitude: 42.7875,
    longitude: -86.1089,
    flowerType: "Tulip",
    bloomStartMonth: 5,
    bloomEndMonth: 5,
    bestViewingMonth: 5,
    bestViewingText: "Early May",
    peakWindow: "First half of May",
    confidence: "medium",
    variabilityNote: "Festival timing and spring temperatures both matter.",
    shortDescription: "A cheerful tulip festival destination with a small-town atmosphere and strong seasonal identity.",
    whyVisit: "Good for travelers who want a compact, easy flower trip in the U.S.",
    travelTags: ["festival", "easy trip", "family friendly"],
    bestTripLength: "2–3 days",
    imageHint: "Holland Michigan tulip festival",
  },
  {
    id: "canberra-tulip",
    destination: "Canberra",
    country: "Australia",
    region: "Oceania",
    latitude: -35.2809,
    longitude: 149.13,
    flowerType: "Tulip",
    bloomStartMonth: 9,
    bloomEndMonth: 10,
    bestViewingMonth: 9,
    bestViewingText: "Mid September",
    peakWindow: "Second half of September",
    confidence: "medium",
    variabilityNote: "Festival beds look strongest during the main spring planting window.",
    shortDescription: "Formal lakeside displays and broad civic gardens give the Southern Hemisphere spring season a polished, easy-to-read anchor.",
    whyVisit: "A strong September choice if you want a classic flower event with an easy capital-city layout.",
    travelTags: ["festival", "city", "easy trip"],
    bestTripLength: "2–4 days",
    imageHint: "Canberra Floriade tulips by lake",
  },
  {
    id: "namaqualand-wildflower",
    destination: "Namaqualand",
    country: "South Africa",
    region: "Africa",
    latitude: -29.3123,
    longitude: 17.8765,
    flowerType: "Wildflower",
    bloomStartMonth: 8,
    bloomEndMonth: 9,
    bestViewingMonth: 9,
    bestViewingText: "Late August to early September",
    peakWindow: "Early September",
    confidence: "low",
    variabilityNote: "Rainfall has a major impact on how dramatic the desert bloom becomes each year.",
    shortDescription: "A rare desert flower season where open landscapes can briefly turn into wide carpets of color.",
    whyVisit: "Best for travelers who want something less expected than garden-based bloom trips.",
    travelTags: ["iconic", "nature", "road trip"],
    bestTripLength: "4–6 days",
    imageHint: "Namaqualand wildflowers desert bloom",
  },
  {
    id: "cape-town-protea",
    destination: "Cape Town",
    country: "South Africa",
    region: "Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    flowerType: "Protea",
    bloomStartMonth: 1,
    bloomEndMonth: 3,
    bestViewingMonth: 2,
    bestViewingText: "February",
    peakWindow: "Mid February",
    confidence: "medium",
    variabilityNote: "Wild protea displays vary by slope, heat, and local rainfall patterns.",
    shortDescription: "Mountain light, fynbos landscapes, and sculptural native blooms create a more dramatic kind of flower trip.",
    whyVisit: "A good warm-season option if you want flowers framed by coastal scenery rather than formal parks.",
    travelTags: ["nature", "coastal", "iconic"],
    bestTripLength: "4–6 days",
    imageHint: "Cape Town protea fynbos bloom",
  },
  {
    id: "grafton-jacaranda",
    destination: "Grafton",
    country: "Australia",
    region: "Oceania",
    latitude: -29.6813,
    longitude: 152.9333,
    flowerType: "Jacaranda",
    bloomStartMonth: 10,
    bloomEndMonth: 11,
    bestViewingMonth: 10,
    bestViewingText: "Late October",
    peakWindow: "Final week of October",
    confidence: "medium",
    variabilityNote: "Storms and wind can shorten the cleanest flowering phase.",
    shortDescription: "A smaller Australian river city that leans fully into jacaranda season with avenues, parks, and a festival atmosphere.",
    whyVisit: "Ideal if you want a more flower-centric jacaranda trip than a larger city usually offers.",
    travelTags: ["festival", "city", "romantic"],
    bestTripLength: "2–3 days",
    imageHint: "Grafton jacaranda avenue Australia",
  },
  {
    id: "taipei-plum-blossom",
    destination: "Taipei",
    country: "Taiwan",
    region: "Asia",
    latitude: 25.033,
    longitude: 121.5654,
    flowerType: "Plum Blossom",
    bloomStartMonth: 1,
    bloomEndMonth: 2,
    bestViewingMonth: 1,
    bestViewingText: "Late January",
    peakWindow: "Last week of January",
    confidence: "medium",
    variabilityNote: "Cool spells help the season hold a little longer at higher elevations.",
    shortDescription: "A gentle winter bloom option with quick access to temple hillsides, tea country, and cooler mountain gardens.",
    whyVisit: "Useful for travelers who want a short winter flower trip without waiting for March.",
    travelTags: ["city", "mountain", "easy trip"],
    bestTripLength: "2–4 days",
    imageHint: "Taipei plum blossom mountain garden",
  },
  {
    id: "mendoza-lavender",
    destination: "Mendoza",
    country: "Argentina",
    region: "South America",
    latitude: -32.8895,
    longitude: -68.8458,
    flowerType: "Lavender",
    bloomStartMonth: 12,
    bloomEndMonth: 1,
    bestViewingMonth: 12,
    bestViewingText: "Mid December to early January",
    peakWindow: "Late December",
    confidence: "low",
    variabilityNote: "Field quality depends on local farm schedules and summer heat.",
    shortDescription: "A vineyard-framed summer escape where pockets of lavender add scent and color to a relaxed wine-country trip.",
    whyVisit: "A credible December option for users who want bloom-inspired travel during Northern Hemisphere off-season.",
    travelTags: ["romantic", "scenic", "easy trip"],
    bestTripLength: "3–4 days",
    imageHint: "Mendoza lavender field vineyard summer",
  },
  {
    id: "santiago-rose-garden",
    destination: "Santiago",
    country: "Chile",
    region: "South America",
    latitude: -33.4489,
    longitude: -70.6693,
    flowerType: "Rose",
    bloomStartMonth: 11,
    bloomEndMonth: 12,
    bestViewingMonth: 11,
    bestViewingText: "November",
    peakWindow: "Mid November",
    confidence: "low",
    variabilityNote: "Urban garden performance changes with water and heat conditions.",
    shortDescription: "A spring city break with formal rose displays, mountain light, and a softer shoulder-season pace.",
    whyVisit: "A sensible shortlist option if you want South America to remain active in late spring.",
    travelTags: ["city", "walkable", "easy trip"],
    bestTripLength: "3–4 days",
    imageHint: "Santiago rose garden spring",
  },
  {
    id: "brisbane-jacaranda",
    destination: "Brisbane",
    country: "Australia",
    region: "Oceania",
    latitude: -27.4698,
    longitude: 153.0251,
    flowerType: "Jacaranda",
    bloomStartMonth: 10,
    bloomEndMonth: 11,
    bestViewingMonth: 10,
    bestViewingText: "October",
    peakWindow: "Mid October",
    confidence: "medium",
    variabilityNote: "Storm activity can drop petals quickly once the season peaks.",
    shortDescription: "Warm spring weather and blooming campus streets make this a lighter, more casual jacaranda city escape.",
    whyVisit: "A good alternative to Sydney if you want the same flower mood with a subtropical pace.",
    travelTags: ["city", "easy trip", "walkable"],
    bestTripLength: "2–4 days",
    imageHint: "Brisbane jacaranda bloom campus streets",
  },
];

export const DESTINATIONS: Destination[] = RAW_DESTINATIONS.map((destination) => ({
  id: destination.id,
  destination: destination.destination,
  name: destination.destination,
  country: destination.country,
  region: destination.region,
  flowerType: destination.flowerType,
  latitude: destination.latitude,
  longitude: destination.longitude,
  bloomStartMonth: destination.bloomStartMonth,
  bloomEndMonth: destination.bloomEndMonth,
  bestViewingMonth: destination.bestViewingMonth,
  bloomStartText: `${getMonthLabel(destination.bloomStartMonth)} opens the season`,
  bloomEndText: `${getMonthLabel(destination.bloomEndMonth)} is usually the trailing edge`,
  bestViewingText: destination.bestViewingText,
  peakWindow: destination.peakWindow,
  bloomMonths: getBloomMonths(destination.bloomStartMonth, destination.bloomEndMonth),
  peakMonths: [destination.bestViewingMonth],
  coordinates: {
    lat: destination.latitude,
    lng: destination.longitude,
  },
  shortDescription: destination.shortDescription,
  whyVisit: destination.whyVisit,
  longDescription: `${destination.shortDescription} ${destination.whyVisit}`,
  signatureExperience: `Best viewing: ${destination.bestViewingText}. Peak window: ${destination.peakWindow}.`,
  travelTip: destination.variabilityNote,
  travelTags: destination.travelTags,
  idealTripLength: destination.bestTripLength,
  bestTripLength: destination.bestTripLength,
  badges: getBadges(destination.travelTags, destination.bestTripLength, destination.confidence),
  confidence: destination.confidence,
  variabilityNote: destination.variabilityNote,
  imageHint: destination.imageHint,
  imageUrl: undefined,
  image: FLOWER_GRADIENTS[destination.flowerType],
}));
